# Generated by Django 2.0.2 on 2018-03-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Temat')),
                ('content', models.TextField(null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.Student')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.SchoolSubject')),
            ],
        ),
    ]
