# Generated by Django 2.0.2 on 2018-03-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('present', models.NullBooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.Student')),
            ],
        ),
    ]
